import { LegalLayout, legalStyles as s } from "./legal-layout";
import { C } from "./shared";

export function PrivacyPolicy() {
  return (
    <LegalLayout>
      <div style={s.badge}>Legal</div>
      <h1 style={s.pageTitle}>Privacy Policy</h1>
      <p style={s.meta}>
        <strong style={s.strong}>Walnutt</strong> · Operated by 3P Labs Private Limited<br />
        <strong style={s.strong}>Effective Date:</strong> 1 March 2026<br />
        <strong style={s.strong}>Last Updated:</strong> 28 February 2026
      </p>

      <p style={s.intro}>
        This Privacy Policy explains how 3P Labs Private Limited ("Walnutt," "we," "us," or "our") collects, uses, stores, and protects your information when you use the Walnutt platform, website (walnutt.com), and related services (collectively, the "Platform"). This policy applies to all users of the Platform, including engineers ("Candidates") and hiring companies ("Companies").
      </p>
      <p style={s.p}>
        By accessing or using the Platform, you agree to the practices described in this Privacy Policy. If you do not agree, please do not use the Platform.
      </p>

      <hr style={s.divider} />

      {/* 1 */}
      <h2 style={s.h2}>1. Information We Collect</h2>

      <h3 style={s.h3}>1.1 Information You Provide</h3>

      <p style={{ ...s.p, fontWeight: 600 }}>Candidates:</p>
      <ul style={s.ul}>
        <li style={s.li}>Full name and email address</li>
        <li style={s.li}>Target role and experience level</li>
        <li style={s.li}>Assessment responses and answers</li>
        <li style={s.li}>GitHub profile URL and linked portfolio content</li>
        <li style={s.li}>Resume or work history (if uploaded)</li>
        <li style={s.li}>Any additional information you choose to share on your Walnutt profile</li>
      </ul>

      <p style={{ ...s.p, fontWeight: 600 }}>Companies:</p>
      <ul style={s.ul}>
        <li style={s.li}>Company name and business email address</li>
        <li style={s.li}>Contact person name and designation</li>
        <li style={s.li}>Job descriptions, role requirements, and hiring preferences</li>
      </ul>

      <h3 style={s.h3}>1.2 Information Generated by Our Platform</h3>
      <ul style={s.ul}>
        <li style={s.li}><strong style={s.strong}>Assessment scores and readiness metrics</strong>: generated by our AI-powered assessment engine based on your responses</li>
        <li style={s.li}><strong style={s.strong}>Skill dimension breakdowns</strong>: AI-evaluated scores across engineering dimensions such as system design, code quality, debugging, and others</li>
        <li style={s.li}><strong style={s.strong}>AI interview transcripts and evaluations</strong>: generated when our AI conducts structured technical interviews</li>
        <li style={s.li}><strong style={s.strong}>AI mentor interaction logs</strong>: records of guidance and recommendations provided by our AI mentor during the learning phase</li>
        <li style={s.li}><strong style={s.strong}>Candidate-company match scores</strong>: AI-generated compatibility scores between candidate profiles and job descriptions</li>
      </ul>

      <h3 style={s.h3}>1.3 Information Collected Automatically</h3>
      <ul style={s.ul}>
        <li style={s.li}>Device information (browser type, operating system, device type)</li>
        <li style={s.li}>IP address and approximate location (city/region level)</li>
        <li style={s.li}>Usage data (pages visited, time spent, features used, assessment completion patterns)</li>
        <li style={s.li}>Cookies and similar tracking technologies (see Section 7)</li>
      </ul>

      <hr style={s.divider} />

      {/* 2 */}
      <h2 style={s.h2}>2. How We Use Your Information</h2>
      <p style={s.p}>We use the information we collect for the following purposes:</p>

      <p style={{ ...s.p, fontWeight: 600 }}>To deliver core platform services:</p>
      <ul style={s.ul}>
        <li style={s.li}>Administering AI-powered adaptive assessments tailored to your target role</li>
        <li style={s.li}>Generating readiness scores and skill dimension breakdowns</li>
        <li style={s.li}>Conducting AI-powered structured technical interviews</li>
        <li style={s.li}>Providing personalised learning paths and AI mentor guidance</li>
        <li style={s.li}>Matching candidate profiles to company job descriptions</li>
        <li style={s.li}>Enabling companies to review verified candidate profiles</li>
      </ul>

      <p style={{ ...s.p, fontWeight: 600 }}>To improve the Platform:</p>
      <ul style={s.ul}>
        <li style={s.li}>Analysing usage patterns to enhance assessment quality and accuracy</li>
        <li style={s.li}>Training and improving our AI models to provide better evaluations, mentoring, and interviews</li>
        <li style={s.li}>Identifying and fixing technical issues</li>
      </ul>

      <p style={{ ...s.p, fontWeight: 600 }}>To communicate with you:</p>
      <ul style={s.ul}>
        <li style={s.li}>Sending account-related notifications</li>
        <li style={s.li}>Sharing assessment results and profile updates</li>
        <li style={s.li}>Notifying candidates of relevant opportunities (with consent)</li>
        <li style={s.li}>Responding to support requests</li>
      </ul>

      <p style={{ ...s.p, fontWeight: 600 }}>To protect the Platform:</p>
      <ul style={s.ul}>
        <li style={s.li}>Detecting and preventing fraud, abuse, or unauthorised access</li>
        <li style={s.li}>Enforcing our Terms and Conditions</li>
      </ul>

      <hr style={s.divider} />

      {/* 3 */}
      <h2 style={s.h2}>3. How Our AI Works With Your Data</h2>
      <p style={s.p}>Walnutt uses artificial intelligence and machine learning across several core functions of the Platform. We believe in being transparent about how AI interacts with your data.</p>

      <p style={s.p}><strong style={s.strong}>AI-Powered Assessments:</strong> When you take an assessment, our AI engine adapts questions in real time based on your responses. It evaluates your answers to generate scores across multiple engineering dimensions. The AI analyses your problem-solving approach, technical reasoning, and decision-making, not just whether an answer is correct.</p>

      <p style={s.p}><strong style={s.strong}>AI Mentor:</strong> During the learning and skill-building phase, our AI mentor provides personalised guidance, suggests resources, and recommends projects based on your assessment results and progress. The AI processes your interaction history to tailor its recommendations.</p>

      <p style={s.p}><strong style={s.strong}>AI Interviews:</strong> For candidates matched with companies, our AI conducts structured technical interviews calibrated to the role requirements. The AI generates evaluation scorecards based on the interview responses.</p>

      <p style={s.p}><strong style={s.strong}>AI Matching:</strong> Our AI processes candidate skill profiles and company job descriptions to generate compatibility match scores.</p>

      <div style={{
        padding: 20, borderRadius: 12, background: "#FFF9F0",
        border: "1px solid rgba(200,160,80,0.2)", marginTop: 16, marginBottom: 14,
      }}>
        <p style={{ ...s.p, fontWeight: 600, margin: "0 0 8px", color: C.black }}>Important notes about our AI:</p>
        <ul style={{ ...s.ul, margin: 0 }}>
          <li style={s.li}>AI-generated scores and evaluations are based on your responses and publicly available information you have linked (such as GitHub profiles). We do not use data from external sources you have not provided or linked.</li>
          <li style={s.li}>Our AI models may be updated and improved over time. When we make significant changes to how AI processes your data, we will update this policy.</li>
          <li style={{ ...s.li, marginBottom: 0 }}>You may request a human review of any AI-generated assessment or evaluation by contacting us at <a href="mailto:privacy@walnutt.com" style={s.email}>privacy@walnutt.com</a>.</li>
        </ul>
      </div>

      <hr style={s.divider} />

      {/* 4 */}
      <h2 style={s.h2}>4. How We Share Your Information</h2>

      <div style={{
        padding: 16, borderRadius: 10, background: C.sageLight,
        border: `1px solid rgba(58,107,76,0.12)`, marginBottom: 16,
      }}>
        <p style={{ fontSize: 15, fontWeight: 700, color: C.sageDark, margin: 0 }}>We do not sell your personal information.</p>
      </div>

      <p style={s.p}>We may share your information in the following circumstances:</p>

      <p style={s.p}><strong style={s.strong}>With Companies (for Candidates):</strong> When you opt to make your profile visible, companies on the Platform can view your Walnutt skill profile, including your readiness score, dimension breakdowns, and linked portfolio. Companies cannot see your raw assessment responses, only the evaluated results.</p>

      <p style={s.p}><strong style={s.strong}>With Candidates (for Companies):</strong> Your company name, role descriptions, and hiring preferences may be visible to matched candidates.</p>

      <p style={s.p}><strong style={s.strong}>Service Providers:</strong> We may share information with trusted third-party service providers who assist us in operating the Platform (hosting, analytics, email delivery). These providers are contractually bound to use your data only for the purposes we specify.</p>

      <p style={s.p}><strong style={s.strong}>Legal Requirements:</strong> We may disclose information if required by law, regulation, legal process, or enforceable government request.</p>

      <p style={s.p}><strong style={s.strong}>Business Transfers:</strong> In the event of a merger, acquisition, or sale of assets, your information may be transferred as part of that transaction. We will notify you of any such change.</p>

      <hr style={s.divider} />

      {/* 5 */}
      <h2 style={s.h2}>5. Data Storage and Security</h2>
      <ul style={s.ul}>
        <li style={s.li}>Your data is stored on secure servers located in India.</li>
        <li style={s.li}>We implement industry-standard technical and organisational security measures, including encryption of data in transit (TLS) and at rest, access controls, and regular security assessments.</li>
        <li style={s.li}>While we take reasonable steps to protect your information, no method of transmission or storage is completely secure. We cannot guarantee absolute security.</li>
      </ul>

      <hr style={s.divider} />

      {/* 6 */}
      <h2 style={s.h2}>6. Data Retention</h2>
      <ul style={s.ul}>
        <li style={s.li}><strong style={s.strong}>Account data</strong> (name, email) is retained for as long as your account is active.</li>
        <li style={s.li}><strong style={s.strong}>Assessment data</strong> (responses, scores, AI evaluations) is retained for as long as your account is active and for up to 12 months after account deletion, to allow for any pending processes or disputes.</li>
        <li style={s.li}><strong style={s.strong}>AI interview data</strong> is retained for 12 months after the interview date.</li>
        <li style={s.li}><strong style={s.strong}>Usage and analytics data</strong> is retained in anonymised form and may be kept indefinitely for platform improvement.</li>
        <li style={s.li}>You may request deletion of your data at any time (see Section 8).</li>
      </ul>

      <hr style={s.divider} />

      {/* 7 */}
      <h2 style={s.h2}>7. Cookies and Tracking</h2>
      <p style={s.p}>We use cookies and similar technologies to:</p>
      <ul style={s.ul}>
        <li style={s.li}>Keep you logged in and maintain your session</li>
        <li style={s.li}>Remember your preferences</li>
        <li style={s.li}>Analyse how the Platform is used (via analytics tools)</li>
      </ul>
      <p style={s.p}>You can control cookies through your browser settings. Disabling cookies may affect certain features of the Platform.</p>

      <hr style={s.divider} />

      {/* 8 */}
      <h2 style={s.h2}>8. Your Rights</h2>
      <p style={s.p}>Under applicable Indian law, including the Digital Personal Data Protection Act, 2023 (DPDPA), you have the following rights:</p>
      <ul style={s.ul}>
        <li style={s.li}><strong style={s.strong}>Right to Access:</strong> Request a copy of the personal data we hold about you.</li>
        <li style={s.li}><strong style={s.strong}>Right to Correction:</strong> Request correction of inaccurate or incomplete data.</li>
        <li style={s.li}><strong style={s.strong}>Right to Erasure:</strong> Request deletion of your personal data, subject to legal retention requirements.</li>
        <li style={s.li}><strong style={s.strong}>Right to Withdraw Consent:</strong> Withdraw your consent for data processing at any time. This will not affect the lawfulness of processing carried out before withdrawal.</li>
        <li style={s.li}><strong style={s.strong}>Right to Grievance Redressal:</strong> Raise a complaint about our data practices.</li>
        <li style={s.li}><strong style={s.strong}>Right to Nominate:</strong> Nominate another individual to exercise your rights in the event of your death or incapacity.</li>
      </ul>
      <p style={s.p}>To exercise any of these rights, contact us at <a href="mailto:privacy@walnutt.com" style={s.email}>privacy@walnutt.com</a>.</p>
      <p style={s.p}>We will respond to your request within 30 days.</p>

      <hr style={s.divider} />

      {/* 9 */}
      <h2 style={s.h2}>9. Children's Privacy</h2>
      <p style={s.p}>The Platform is not intended for individuals under the age of 18. We do not knowingly collect personal data from children. If we become aware that we have collected data from a person under 18, we will take steps to delete it promptly.</p>

      <hr style={s.divider} />

      {/* 10 */}
      <h2 style={s.h2}>10. Third-Party Links</h2>
      <p style={s.p}>The Platform may contain links to third-party websites or services (such as GitHub). We are not responsible for the privacy practices of these third parties. We encourage you to read their privacy policies.</p>

      <hr style={s.divider} />

      {/* 11 */}
      <h2 style={s.h2}>11. Changes to This Policy</h2>
      <p style={s.p}>We may update this Privacy Policy from time to time. When we make material changes, we will notify you by updating the "Last Updated" date at the top and, where appropriate, by email or through the Platform. Your continued use of the Platform after changes constitutes acceptance of the updated policy.</p>

      <hr style={s.divider} />

      {/* 12 */}
      <h2 style={s.h2}>12. Contact Us</h2>
      <p style={s.p}>If you have questions, concerns, or requests regarding this Privacy Policy or our data practices:</p>
      <div style={{
        padding: 20, borderRadius: 12, background: C.sageLight,
        border: `1px solid rgba(58,107,76,0.12)`,
      }}>
        <p style={{ fontSize: 15, fontWeight: 600, color: C.black, margin: "0 0 4px" }}>3P Labs Private Limited</p>
        <p style={{ fontSize: 14, color: C.gray800, margin: "0 0 2px" }}>Email: <a href="mailto:privacy@walnutt.com" style={s.email}>privacy@walnutt.com</a></p>
        <p style={{ fontSize: 14, color: C.gray800, margin: 0 }}>Website: walnutt.com</p>
      </div>

      <p style={{ ...s.p, marginTop: 32, fontStyle: "italic", color: C.gray500 }}>
        This Privacy Policy is governed by the laws of India.
      </p>
    </LegalLayout>
  );
}